### ISSUE TITLE
; delimiter

### ISSUE THREAD

**Issue by Spoutnik97** [weartist/zed-rainbow-csv#2]
Hi,
currently, the extension considers only the "," delimiter.

How could we add the ";" delimiter ? 

I use it because some cells contains comma in sentences

**Comment by weartist** [comment]
> Hi, currently, the extension considers only the "," delimiter.
> 
> How could we add the ";" delimiter ?
> 
> I use it because some cells contains comma in sentences

Sorry I overlooked this format before, I'll provide support as soon as possible

**Comment by weartist** [comment]
> Hi, currently, the extension considers only the "," delimiter.
> 
> How could we add the ";" delimiter ?
> 
> I use it because some cells contains comma in sentences

https://github.com/zed-industries/extensions/pull/684 I submitted an update to support semicolons, thank you for your feedback!
