### ISSUE TITLE
Support pipe delimited files

### ISSUE THREAD

**Issue by isaacvando** [weartist/zed-rainbow-csv#3]
It would be nice to have support for pipe (`|`) delimited CSVs. Thanks for making this!

**Comment by weartist** [comment]
> It would be nice to have support for pipe (`|`) delimited CSVs. Thanks for making this!

Thank you so much! Support for pipe has been submitted~
https://github.com/zed-industries/extensions/pull/956

**Comment by isaacvando** [comment]
Awesome, thanks for doing that!
